title: Introduction to Machine Learning Workshop
logo: /assets/img/logo.gif
description: Monday, July 31 & Tuesday, August 1, 2022  |  1:00 PM - 4:00 AM PDT
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
