title: Introduction to Machine Learning Workshop
logo: /assets/img/logo.gif
description: Monday, August 8 & Tuesday, August 9, 2022  |  8:00 AM - 11:00 AM PDT
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
